CREATE TABLE users(
	id				VARCHAR(10) PRIMARY KEY,
	NAME			VARCHAR(20) NOT NULL,
	PASSWORD		VARCHAR(20) NOT NULL
);

DESC users;

SELECT * FROM users;

DELETE FROM users;


CREATE USER toby@localhost IDENTIFIED BY '2222';

-- CREATE DATABASE testdb;
CREATE SCHEMA testdb DEFAULT CHARACTER SET UTF8;

GRANT ALL PRIVILEGES ON testdb.* TO toby@localhost;

SHOW DATABASES;



CREATE TABLE book(
	title		VARCHAR(30) PRIMARY KEY,
	auth		VARCHAR(30) NOT NULL,
	price		INT NOT NULL
);

DESC book;
SELECT * FROM book;
DELETE FROM book;