CREATE TABLE users(
	id				VARCHAR(10) PRIMARY KEY,
	NAME			VARCHAR(20) NOT NULL,
	PASSWORD		VARCHAR(20) NOT NULL
);

DESC users;

SELECT * FROM users;

DELETE FROM users;


CREATE USER toby@localhost IDENTIFIED BY '2222';

-- CREATE DATABASE testdb;
CREATE SCHEMA testdb DEFAULT CHARACTER SET UTF8;

GRANT ALL PRIVILEGES ON testdb.* TO toby@localhost;

SHOW DATABASES;



CREATE TABLE myBoard(
	idx			INT AUTO_INCREMENT PRIMARY KEY,
	writerID		VARCHAR(30) NOT NULL,
	title			VARCHAR(100) NOT NULL,
	content		VARCHAR(500) NOT NULL,
	writeDate	TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	watch			INT DEFAULT 0
);

DESC myBoard;

SELECT * FROM myBoard;

DELETE FROM myBoard;