CREATE TABLE users(
	id				VARCHAR(10) PRIMARY KEY,
	NAME			VARCHAR(20) NOT NULL,
	PASSWORD		VARCHAR(20) NOT NULL
);

DESC users;

SELECT * FROM users ORDER BY email asc;

DELETE FROM users;


ALTER TABLE users ADD COLUMN email VARCHAR(50) NOT NULL;


CREATE USER toby@localhost IDENTIFIED BY '2222';

-- CREATE DATABASE testdb;
CREATE SCHEMA testdb DEFAULT CHARACTER SET UTF8;

GRANT ALL PRIVILEGES ON testdb.* TO toby@localhost;

SHOW DATABASES;

ALTER TABLE users DROP COLUMN recommand;
ALTER TABLE users ADD COLUMN recommend INT;